trigger:
  branches:
    include:
    - myproject
resources:
  repositories:
  - repository: self
variables:
- name: tag
  value: '$(Build.BuildId)'
- name: dockerComposePath
  value: /tmp/brecky
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      inputs:
        targetType: inline
        script: |
          sudo mkdir $(dockerComposePath)
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.40.3/docker-compose-linux-x86_64 -o $(dockerComposePath)/docker-compose
          sudo chmod 755 $(dockerComposePath)/docker-compose
          #displayName: Download docker-compose
    - task: DockerCompose@1
      inputs:
        action: 'Run a Docker Compose command'
        dockerComposeFile: '**/azure-pipelines/docker-compose-build.yaml'
        dockerComposeCommand: 'build amd64-ffmpeg'
        dockerComposePath: $(dockerComposePath)/docker-compose
