

FROM ubuntu:noble AS build

WORKDIR /tmp/workdir

ARG MAKEFLAGS=-j4


ENV \
  OPENCOREAMR_VERSION=0.1.6 \
  DEBIAN_FRONTEND=noninteractive \
  SRC=/usr/local \
  PATH=/usr/custom_cmake/bin:$PATH \
  PKG_CONFIG_PATH="/opt/ffmpeg/share/pkgconfig:/opt/ffmpeg/lib/pkgconfig:/opt/ffmpeg/lib64/pkgconfig" \
  PREFIX=/opt/ffmpeg \
  LD_LIBRARY_PATH="/opt/ffmpeg/lib:/opt/ffmpeg/lib64:/usr/lib64:/usr/lib:/lib64:/lib"

RUN buildDeps="autoconf \
  automake \
  ca-certificates \
  cmake \
  curl \
  bzip2 \
  libexpat1-dev \
  g++ \
  gcc \
  git \
  gperf \
  libtool \
  make \
  nasm \
  perl \
  pkg-config \
  python3 \
  libssl-dev \
  yasm \
  libgomp1 \
  libnuma-dev \
  zlib1g-dev \
  libmfx-dev \
  libva-dev" && \
  apt-get -yqq update && \
  apt-get install -yq --no-install-recommends ${buildDeps}


FROM scratch
COPY --from=build /usr/local /usr/local/
