
FROM nvidia/cuda:13.1.1-devel-ubuntu24.04 AS build

WORKDIR /tmp/workdir

RUN \ 
  apt-get -y update && \
  apt-get install -y \
  build-essential \ 
  yasm \
  cmake \
  libtool \
  libc6 \
  libc6-dev \
  unzip wget \
  libnuma1 \
  libnuma-dev

#Clone ffnvcodec
RUN git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
#Install ffnvcodec
RUN cd nv-codec-headers && sudo make install && cd –
#Clone FFmpeg’s public GIT repository.
RUN git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg/
#Configure
RUN ./configure \
  --enable-nonfree \
  --enable-cuda-nvcc \
  --enable-libnpp \
  --extra-cflags=-I/usr/local/cuda/include \
  --extra-ldflags=-L/usr/local/cuda/lib64 \
  --disable-static --enable-shared
#Compile
RUN make -j 8
#Install the libraries.
RUN make install

FROM scratch

